apiVersion: v1
kind: Service
metadata:
  name: basketservice-srv
spec:
  type: NodePort
  selector:
    app: basketservice
  ports:
    - name: basketservice
      protocol: TCP
      port: 80
      targetPort: 80
